/************************************************************************************************************************************************************
 * @file Ex_15_29.cpp
 * @brief Exercise 15.29: Repeat your program, but this time store shared_ptrs to objects of type Quote. Explain
 * any discrepancy in the sum generated by the this version and the previous program. If there is no discrepancy, 
 * explain why there isn’t one.
 * @date 2024-02-05
 * 
 * @copyright Copyright (c) 2024
 * 
 *************************************************************************************************************************************************************/

#include <iostream>
#include "Ex_15_27_DiscQuote.cpp" 
#include <vector>
#include <memory>

int main(){
    std::vector<std::shared_ptr<Quote>>  basket;
    basket.push_back(std::make_shared<Bulk_quote>("c++ primer", 56, 0.4,50));
    basket.push_back(std::make_shared<Bulk_quote>("discrete math", 76, 0.2, 100));
    basket.push_back(std::make_shared<Bulk_quote>("advanced c", 36, 0.3 , 100));
    basket.push_back(std::make_shared<Bulk_quote>("Java", 46, 0.2, 50));

    for( auto iter = basket.begin(); iter != basket.end(); ++iter){
        std::cout << (*iter)->net_price(100) << std::endl;
    }

    return 0;
}