# Site settings
title: My Blog
author:
  name: Vijai Shankar
  email: missingsemicolon.vijai@gmail.com
description: "Solutions to C++ Primer 5th Editions"

# Build settings
remote_theme: jekyll/minima